/* Scope the VYRLE mockup CSS under .vy-app so it cannot leak into the rest of the app. */
const fs = require('fs');
const postcss = require('postcss');

const html = fs.readFileSync('mock.tmp.html', 'utf8');
const css = html.match(/<style>([\s\S]*?)<\/style>/)[1];

const ROOT = '.vy-app';
function scopeSelector(sel) {
  const s = sel.trim();
  if (!s) return s;
  if (s.startsWith(ROOT)) return s;
  if (s === ':root' || s === 'html' || s === 'body') return ROOT;
  // leading html/body/:root → replace with root scope
  let m = s.match(/^(?::root|html|body)\b(.*)$/);
  if (m) return ROOT + (m[1].startsWith(' ') || m[1] === '' ? m[1] : ' ' + m[1]);
  if (s.startsWith('*')) return ROOT + ' ' + s;
  return ROOT + ' ' + s;
}

const root = postcss.parse(css);
root.walkRules((rule) => {
  const p = rule.parent;
  if (p && p.type === 'atrule' && /keyframes/i.test(p.name)) return; // leave keyframe stops
  rule.selectors = rule.selectors.map(scopeSelector);
});

const out =
  '/* ============================================================\n' +
  '   VYRLE creator dashboard — the actual mockup CSS, scoped under\n' +
  '   .vy-app (auto-generated by scope-css.cjs). Do not hand-edit;\n' +
  '   edit the mockup + regenerate, or add overrides in vyrle.extra.css.\n' +
  '   ============================================================ */\n' +
  root.toString();

fs.writeFileSync('src/styles/vyrle.css', out);
console.log('wrote src/styles/vyrle.css', out.length, 'bytes');
